### FastText
- Word2Vec에서 OOV(Out Of Voca) 문제를 해결하기 위한 모델
- Word2Vec은 '강아지'와 '강아지들' 두 단어를 다른 단어로 생각
- FastText는 기존의 Word2Vec 학습 방식은 동일하지만 기준이 되는 문자가 다름
    - Word2Vec는 단어를 기준, FastText는 글자를 기준
    - '강아지' -> '강', '아', '지', '강아', '아지', '강아지' (n-gram 방식)
    - subword를 기준으로 문자들을 벡터화
    - Word2Vec의 매개변수들을 이용하지만 추가적으로 subword 관련한 매개변수들이 사용
        - 최소 길이의 subword : min_n (기본값은 3)
        - 최대 길이의 subword : max_n (기본값은 6)
        - min_n = 1, max_n = 1 로 설정을 하면 subword 사용 금지 -> Word2Vec 방식을 이용
        - min_n이 max_n보다 작거나 같게 설정
        - bucket매개변수는 단어(subword) 사전에 개수를 제한 (메모리 과부하 방지 위함)

In [2]:
from gensim.models import Word2Vec, FastText

In [ ]:
sentences=[
    ['이커머스', '데이터', '분석', '진행'],
    ['상품', '리뷰', '감성', '분석', '합니다'],
    ['형태소', '단위', '임베딩', '가능']
]

model_wv=Word2Vec(
    sentences=sentences,
    window=3,
    vector_size=50,
    min_count=1,
    sg=1,
    epochs=10
)

In [ ]:
model_ft=FastText(
    sentences=sentences,
    window=3,
    vector_size=50,
    min_count=1,
    sg=1,
    epochs=10,
    min_n=2,
    max_n=4
)

In [5]:
#특정 단어의 단위 벡터 출력
model_wv.wv['이커머스']

array([ 0.0054888 , -0.0167182 ,  0.01571161,  0.01707221, -0.01916817,
        0.00489253,  0.01980994, -0.01533161, -0.01393384, -0.01547303,
        0.01679185, -0.00136267,  0.01828882, -0.01631644,  0.00748617,
        0.00527009,  0.00148543,  0.00465535, -0.01493819, -0.01871675,
        0.00470915,  0.01229691,  0.01597138,  0.01147179, -0.00155467,
        0.01661233, -0.01867263,  0.00681227,  0.00053351,  0.00771449,
        0.01477157, -0.01345033,  0.01116896, -0.01904445, -0.00160892,
       -0.01737747, -0.01019735,  0.01857845, -0.00371652,  0.00582885,
        0.01814256,  0.01787627, -0.01641687, -0.00602463,  0.01977321,
        0.01020886, -0.00317617, -0.01738404,  0.00592303, -0.0133518 ],
      dtype=float32)

In [6]:
model_ft.wv['이커머스']

array([ 0.00162357, -0.00056922,  0.00173105,  0.00058287,  0.00228292,
       -0.00345264, -0.00250777, -0.00061342,  0.00105306, -0.00115158,
       -0.00488795, -0.0014066 ,  0.0016283 , -0.00409494, -0.00358815,
        0.00067187, -0.00421643,  0.00460635, -0.00176343, -0.00177863,
       -0.00093921,  0.00316563, -0.00431955,  0.00661633, -0.00447367,
        0.00399939, -0.00105594, -0.00369431, -0.00305687, -0.00117266,
        0.00038306, -0.00507055,  0.00180291, -0.00104463, -0.0036624 ,
       -0.00555523, -0.00221067,  0.0058679 ,  0.00027384,  0.00263351,
        0.00616281, -0.00194953, -0.00014901, -0.00482749,  0.0019421 ,
       -0.00037889, -0.0017121 , -0.00555988,  0.0011939 ,  0.00359156],
      dtype=float32)

In [ ]:
#단어 간의 유사도
model_wv.wv.most_similar('데이터', topn=3)

[('상품', 0.23735211789608002),
 ('감성', 0.16942839324474335),
 ('임베딩', 0.12119603902101517)]

In [8]:
model_ft.wv.most_similar('데이터', topn=3)

[('이커머스', 0.2815113663673401),
 ('리뷰', 0.2239587903022766),
 ('감성', 0.11446578800678253)]

In [10]:
#단어 사전에 없는 단어를 이용해서 단위 벡터를 생성한다?
#Word2Vec는 단어 사전에 없는 단어는 단위 벡터화가 불가능
# model_wv.wv['감정']

model_ft.wv['감정']     #FastText는 생성 가능

array([-5.5013038e-03, -2.2984333e-03, -2.5746336e-03,  4.0548532e-03,
        5.9943744e-03,  7.8264624e-05, -3.3545090e-04,  1.2387059e-03,
       -5.6768395e-03, -1.9010300e-03,  5.5366976e-04, -4.3595689e-03,
        1.8590745e-03, -1.6518733e-03,  1.2153280e-03,  4.9256044e-03,
       -1.0720458e-03,  1.6735088e-03, -7.5531560e-03,  9.4417931e-04,
       -3.0814651e-03, -4.9539204e-03,  6.7936658e-04,  2.4488713e-03,
        1.9779969e-03, -2.2291213e-03, -3.4819357e-04,  4.1451180e-04,
        7.0494809e-03,  1.9069822e-03, -4.7397302e-03,  1.0020767e-02,
        5.4202713e-03,  6.6833706e-03, -7.0033087e-03,  3.0828323e-03,
        4.4808686e-03,  1.0817967e-02,  4.6292976e-03,  2.7071603e-03,
       -4.2115338e-03, -4.7755633e-03,  2.4743299e-03, -2.6541401e-03,
        9.1218473e-03, -2.9161153e-04,  4.3157893e-04, -6.9790217e-03,
        4.6274550e-03,  2.2755230e-03], dtype=float32)

In [ ]:
#단어 사전에 없는 단어로 유사한 단어를 찾을 수 있을까?
model_wv.wv.most_similar('감정',topn=3)     #못 찾음

In [13]:
model_ft.wv.most_similar('감정',topn=3)

[('가능', 0.18830130994319916),
 ('형태소', 0.18508748710155487),
 ('감성', 0.1764506846666336)]

In [18]:
sentences2=[
    ['고양이', '고양이들', '귀엽다', '동물', '반려동물'],
    ['강아지', '강아지들', '귀엽다', '동물', '반려동물'],
    ['달리다', '달리는', '달림', '걷다', '걷는'],
    ['예쁘다', '예쁨', '예쁜', '매력적이다'],
    ['컴퓨터', '컴퓨팅', '컴퓨터들', '기계']
]

In [19]:
w2v=Word2Vec(
    sentences=sentences2,
    window=3,
    min_count=1,
    sg=1,
    seed=42
)

ft=FastText(
    sentences=sentences2,
    window=3,
    min_count=1,
    sg=1,
    seed=42,
    min_n=2
)

In [20]:
#단어 간의 유사도를 확인
print(
    'Word2Vec 단어 간의 유사도 : ', w2v.wv.similarity('강아지', '강아지들')
)
print(
    'FastText 단어 간의 유사도 : ', ft.wv.similarity('강아지', '강아지들')
)

Word2Vec 단어 간의 유사도 :  0.06403736
FastText 단어 간의 유사도 :  0.4059004


In [22]:
#비교 대상 단어들
test_text=[
    ['강아지', '강아지들'],
    ['고양이', '고양이들'],
    ['달리다', '달리는'],
    ['예쁘다', '예쁜'],
    ['컴퓨터', '컴퓨팅'],
    ['달리다', '걷다']
]

for word1, word2 in test_text:
    w2v_sim=w2v.wv.similarity(word1, word2)
    ft_sim=ft.wv.similarity(word1, word2)
    print(f'{word1}과 {word2}간의 유사도 : Word2Vec({w2v_sim}) / FastText({ft_sim})')

강아지과 강아지들간의 유사도 : Word2Vec(0.06403736025094986) / FastText(0.40590038895606995)
고양이과 고양이들간의 유사도 : Word2Vec(-0.07337046414613724) / FastText(0.46013206243515015)
달리다과 달리는간의 유사도 : Word2Vec(0.04628411680459976) / FastText(0.3028862476348877)
예쁘다과 예쁜간의 유사도 : Word2Vec(0.1387229710817337) / FastText(0.06622864305973053)
컴퓨터과 컴퓨팅간의 유사도 : Word2Vec(-0.05135165899991989) / FastText(0.36511483788490295)
달리다과 걷다간의 유사도 : Word2Vec(-0.06980345398187637) / FastText(-0.019979456439614296)


In [23]:
#상품명을 기준으로 특정 상품을 검색 시 연관된 상품의 목록을 확인
products={
    'P001' : '무선 이어폰 블루투스 노이즈캔슬링, 충전케이스',
    'P002' : '유선 이어폰 하이파이 금도금',
    'P003' : '게이밍 마우스 RGB 경량 디자인',
    'P004' : '무선 마우스 초경량 블루투스 듀얼모드',
    'P005' : '헤드폰 노이즈캔슬링 유선'
}

In [26]:
#dict 형태 데이터에서 FastText에서 필요한 데이터는 values
data=products.values()
data

dict_values(['무선 이어폰 블루투스 노이즈캔슬링, 충전케이스', '유선 이어폰 하이파이 금도금', '게이밍 마우스 RGB 경량 디자인', '무선 마우스 초경량 블루투스 듀얼모드', '헤드폰 노이즈캔슬링 유선'])

In [28]:
from konlpy.tag import Komoran

In [29]:
komoran=Komoran()

tokens_komoran=[]
tokens_split=[]
for name in data:
    tokens_komoran.append(komoran.morphs(name))
    tokens_split.append(name.split())

In [30]:
print(tokens_komoran)
print(tokens_split)

[['무선', '이어폰', '블루투스', '노이즈캔슬링', ',', '충전', '케이스'], ['유선', '이어폰', '하이파', '이', '금도금'], ['게이밍', '마우스', 'RGB', '경량', '디자인'], ['무선', '마우스', '초', '경량', '블루투스', '듀얼모드'], ['헤드폰', '노이즈캔슬링', '유선']]
[['무선', '이어폰', '블루투스', '노이즈캔슬링,', '충전케이스'], ['유선', '이어폰', '하이파이', '금도금'], ['게이밍', '마우스', 'RGB', '경량', '디자인'], ['무선', '마우스', '초경량', '블루투스', '듀얼모드'], ['헤드폰', '노이즈캔슬링', '유선']]


In [36]:
ft2=FastText(
    sentences=tokens_split,
    window=3,
    min_count=1,
    sg=1,
    min_n=2,
    max_n=4,
    seed=42,
)

In [37]:
#상품명들을 벡터화
#단어들의 단위 벡터를 구하고 평균을 구한다 -> L2정규화를 이용하여 거리는 1로 변경
import numpy as np

In [90]:
def sent_vector(token, type = None):
    #token : 토큰화된 문장 데이터
    #type : None인 경우는 평규값, 'l2'로 들어오면 L2 정규화
    vectors = []
    for word in token:
        # if word in w2v.wv.index_to_key:
        vectors.append( ft2.wv[word] )
    
    #vectors가 존재하지 않는 경우 
    if not vectors:
        return np.zeros(ft2.vector_size)

    #단위 벡터들의 평균값을 구한다. 
    v = np.mean(vectors, axis=0)

    #type이 만약에 'l2'라면
    if type == 'l2':
        #벡터의 거리로 나눠준다. 
        #벡터의 거리는? ->  numpy의 거리를 구하는 함수 linalg()
        v =  v / ( np.linalg.norm(v) + 1e-12 )

    return v

In [92]:
#token_split을 이용하여 벡터화 
items_vector = []

for token in tokens_split:
    items_vector.append(
        sent_vector(token)
    )

In [93]:
items_vector_l2 = []

for token in tokens_split:
    items_vector_l2.append(
        sent_vector(token, 'l2')
    )

In [94]:
#문장들의 평균 벡터 -> 특정 상품과 비슷한 상품의 이름을 코사인 유사도를 이용하여 관련 상품 목록을 확인
from sklearn.metrics.pairwise import cosine_similarity

In [95]:
idx = list(products.keys()).index('P003')
# list 안에 index()함수는? -> 특정 값의 위치를 출력
idx

2

In [96]:
items_vector[2]

array([-3.1997956e-04,  3.1426892e-04,  5.1835913e-04,  6.5027707e-04,
        3.2890899e-04, -3.2309207e-04, -7.2781651e-05,  1.1447497e-03,
       -6.2428444e-04, -9.9435484e-04, -8.7199983e-04,  2.1038984e-03,
       -7.5986597e-04,  1.0853239e-03, -5.6221231e-04,  1.5602780e-03,
        5.0778093e-04,  9.3692646e-04,  5.4116867e-04, -4.0238985e-04,
       -7.1640546e-04, -1.4906393e-03,  1.8833525e-03, -3.2987967e-04,
        1.4245252e-03,  1.4625288e-03, -7.7995984e-04,  1.9023576e-04,
       -2.1541570e-04,  5.7092413e-05, -1.2823667e-03, -3.3727914e-04,
       -8.7566592e-04,  5.6517322e-04, -6.1921768e-05, -1.4579889e-03,
        1.5861357e-03,  2.5613533e-04,  6.1103003e-04,  1.0379369e-03,
       -9.7191798e-05,  1.1546657e-03,  8.2155800e-04,  1.2236570e-03,
       -8.6209981e-04,  1.6541416e-03,  7.3876913e-04,  7.2025286e-04,
       -4.9226451e-06, -2.4503036e-04, -9.4905205e-04,  1.7282370e-04,
       -1.0806203e-03,  5.1225751e-04, -3.5765735e-04,  9.0596115e-04,
      

In [97]:
cosine_similarity([items_vector[idx]], items_vector)

array([[0.07819747, 0.02050333, 1.0000001 , 0.18784526, 0.11173344]],
      dtype=float32)

In [98]:
cosine_similarity( [ft2.wv['마우스']], items_vector )

array([[0.21567668, 0.11230843, 0.49815714, 0.52489674, 0.26454455]],
      dtype=float32)

In [108]:
# 코사인 유사도를 이용해서 가장 근접한 상품의 이름을 출력하는 함수 
def recommand_by_text(product_id):
    # dict.keys() 특정 아이디의 위치를 확인 
    idx = list(products.keys()).index(product_id)

    # 해당 아이디 위치의 단위 벡터 데이터와 다른 상품들의 단위 벡터 데이터를 코사인 유사도를 이용하여 계산
    sims = cosine_similarity( [ items_vector[idx] ], items_vector ).ravel()
    # 내림차순 정렬 (오름차순 정렬을 역순)
    order = sims.argsort()[::-1]
    print(order)
    # 정렬의 순서를 인덱스로 표시
    # 추천 상품명을 담기 위한 빈 리스트 생성
    result = []
    for i in order:
        # 코사인 유사도가 1인 경우 ? -> i가 위치값 -> list(products.keys())[i]이 값이 product_id와 같은 경우 
        # if list(products.keys())[i] != product_id:
        if sims[i] != 1.0:
            result.append(
                [
                    list(products.values())[i], round(sims[i], 4)
                ]
            )
    return result

In [109]:
recommand_by_text('P003')

[2 3 4 0 1]


[['게이밍 마우스 RGB 경량 디자인', np.float32(1.0)],
 ['무선 마우스 초경량 블루투스 듀얼모드', np.float32(0.1878)],
 ['헤드폰 노이즈캔슬링 유선', np.float32(0.1117)],
 ['무선 이어폰 블루투스 노이즈캔슬링, 충전케이스', np.float32(0.0782)],
 ['유선 이어폰 하이파이 금도금', np.float32(0.0205)]]

#### 문제
- 특정한 검색어를 입력했을 떄, 유사한 상품 목록 3개를 추천하는 함수를 생성
- items_vector_l2, L2 정규화가 된 문장 벡터를 이용하여 코사인 유사도를 구하고 상위의 3개의 추천 상품명을 출력
- '노이즈캔슬링' 입력값을 넣었을 떄 추천 상품 3개의 결과를 확인

In [104]:
def recommand_by_search(text):
    # 검색어를 이용하여 등록된 상품 목록에서 유사한 상품을 추천
    # text를 이용해서 단위 벡터를 생성 l2 정규화가 된 벡터데이터와 코사인 유사도를 활용
    vector = ft2.wv[text] 
    v = vector / (np.linalg.norm(vector) + 1e-12 )

    sims = cosine_similarity( [v], items_vector_l2 ).ravel()

    order = sims.argsort()[::-1]
    print(order[:3])
    result = []
    for i in order[:3]:
        result.append(
            [
                list( products.values() )[i], round(sims[i], 4)
            ]
        )
    return result

In [105]:
recommend_by_search('노이즈캔슬링')

[['헤드폰 노이즈캔슬링 유선', np.float32(0.4383)],
 ['무선 이어폰 블루투스 노이즈캔슬링, 충전케이스', np.float32(0.259)],
 ['무선 마우스 초경량 블루투스 듀얼모드', np.float32(0.0158)]]