In [19]:
import torch
import torch.nn.functional as F

In [20]:
#임의의 문장 임베딩 데이터
#3개의 단어에 각 단어는 4개의 차원의 숫자로 표현
x=torch.randn(3, 4)
x

tensor([[-0.3721, -1.7200,  0.0733, -0.4244],
        [-0.0810,  0.3975, -1.9435, -1.1168],
        [ 0.0888,  0.9141, -1.2625,  1.9264]])

In [21]:
#Query, Key, Value를 임의의 가중치 행렬로 생성 (원래는 학습이 된 가중치 행렬 부분)
w_q=torch.randn(4, 4)
w_k=torch.randn(4, 4)
w_v=torch.randn(4, 4)

In [22]:
#x의 데이터와 각각의 가중치 행렬을 곱하여 q, k, v를 생성
q=torch.matmul(x, w_q)
k=torch.matmul(x, w_k)
v=torch.matmul(x, w_v)

In [23]:
#Attention Score를 생성 -> Query와 Key의 내적
attention_score = torch.matmul(q, k.T)

In [24]:
#Attenion_score는 고차원잀록 발산을 하기 때문에 Key차원 수에 루트를  씌워서 나눠준다.
d_k = k.size(1)

In [25]:
#스케일링과 softmax를 통해서 확률로 변환 (모든 행의 합이 1)
attention_weight = F.softmax(attention_score / (d_k ** 0.5), dim=1)
attention_weight

tensor([[1.6554e-03, 1.1948e-02, 9.8640e-01],
        [1.3635e-04, 1.3998e-03, 9.9846e-01],
        [2.2337e-01, 5.8181e-01, 1.9482e-01]])

In [26]:
output = torch.matmul(attention_weight, v)
output

tensor([[ 3.5143,  1.1928,  0.1852, -0.2520],
        [ 3.4794,  1.2330,  0.1974, -0.2442],
        [ 4.3170, -1.5717, -0.3599, -0.8712]])